package week.on.a.plate.core.theme

import androidx.compose.ui.graphics.Color

val ColorTextBlack = Color(0xFF262626)
val ColorSurfaceBlack = Color(0xFF2C2C2C)
val ColorSubTextGrey = Color(0xFF777777)
val ColorBackgroundWhite = Color(0xFFFFFFFF)
val ColorPanelLightGrey = Color(0xFFF6F6F6)
val ColorPanelEdit = Color(0xFFB9B9B9)
val ColorButtonNegativeGrey = Color(0xFFEAEAEA)
val ColorStrokeGrey = Color(0xFFBFBFBF)
val ColorBluePanel = Color(0xFFDDEFFF)
val ColorBlueButton = Color(0xFFAAD7FF)
val ColorButtonYellowDark = Color(0xFFC29F5D)
val ColorButtonYellow = Color(0xFFFFD17B)
val ColorPanelYellow = Color(0xFFFFE4B9)
val ColorBackgroundYellow = Color(0xFFFFF8EE)
val ColorStrokeBlue = Color(0xFF127CDA)
val ColorDarkButtonGreen = Color(0xFF678754)
val ColorDarkButtonOutlineGreen = Color(0xFF4E6C3C)
val ColorButtonGreenStroke = Color(0xFFADCA8A)
val ColorButtonGreen = Color(0xFFD3F4AB)
val ColorPanelGreen = Color(0xFFEBFFCF)
val ColorTransparent = Color(0x00000000)